name: Flutter Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'

    - name: Verificar Flutter
      run: flutter doctor

    - name: Obtener dependenciasss
      run: |
        cd simulapp
        flutter pub get

    - name: Analizar código
      run: |
        cd simulapp
        flutter analyze --no-fatal-infos

    - name: Build para Android (APK)
      run: |
        cd simulapp
        flutter build apk --release --android-skip-build-dependency-validation

    - name: Crear directorio de release
      run: |
        mkdir release_files
        cp simulapp/build/app/outputs/flutter-apk/app-release.apk release_files/simulapp-${{ github.ref_name }}.apk

    - name: Crear Release en GitHub
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Simulapp ${{ github.ref_name }}"
        body: |
          ## Release ${{ github.ref_name }}
          
          ### Builds incluidos:
          - APK para Android: simulapp-${{ github.ref_name }}.apk
          
          ### Instrucciones:
          - **Android**: Descargar el APK e instalar
        files: |
          release_files/simulapp-*.apk
